---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
      - c912b98b9072ee454c6b02287ffc5697
      - 2db37f8ec9b642b429b3aa34b9c1d943
  fixme:
    enabled: true
    exclude_fingerprints:
      - 383e5a2ad1510b994aea311cbd304b24
      - a9c8653657fccf8bb83bb454e7fb6a1e
      - 02bc740abd74d4bc068af1caf193f370
  rubocop:
    enabled: true
    exclude_fingerprints:
      - 706a8985b81b445c765520fe6a298020
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - ".rvmrc"
  - "nmap_scans.db"
  - "*.swp"
  - "*~"
