---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
      - c912b98b9072ee454c6b02287ffc5697
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
      - 706a8985b81b445c765520fe6a298020
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - ".rvmrc"
  - "nmap_scans.db"
  - "*.swp"
  - "*~"
